on: [ push ]
jobs:
  generate-sboms:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3.5.2

      - name: spdx-sbom
        uses: anchore/sbom-action@v0.14.2
        with:
          format: spdx
          artifact-name: rainbow-sbom.spdx

      - name: cyclonedx-sbom
        uses: anchore/sbom-action@v0.14.2
        with:
          format: cyclonedx-json
          artifact-name: rainbow-sbom-cdx.json